services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_c
    ports:
      - 3000:3000
    volumes:
      - ../Web-Interface-Fraud:/app
      - ../node_modules:/app/node_modules
    # stdin_open: true
    # tty: true